twilio:
  account-sid: ${TWILIO_ACCOUNT_SID}
  auth-token: ${TWILIO_AUTH_TOKEN}
  whatsapp-number: ${TWILIO_WHATSAPP_NUMBER}
  rate-limit: 100 # messages per hour per user

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wish_test
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root123
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
#+14155238886